### ISSUE TITLE
CMake Error at CMakeLists.txt:28 (add_subdirectory):

### ISSUE THREAD

**Issue by jgqandsh** [lessthanoptimal/BoofCPP#2]
I did
root@ggjiang/BoofCPP# mkdir build
root@ggjiang/BoofCPP# cd build
root@ggjiang/BoofCPP# cmake -DCMAKE_BUILD_TYPE=Release ..
I got 
-- Could NOT find JNI (missing:  JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JAVA_INCLUDE_PATH (ADVANCED)
   used as include directory in directory 
   used as include directory in directory 
JAVA_INCLUDE_PATH2 (ADVANCED)
   used as include directory in directory 
   used as include directory in directory 
-- Configuring incomplete, errors occurred!
See also "/root/perf-map-agent/CMakeFiles/CMakeOutput.log".
See also "/root/perf-map-agent/CMakeFiles/CMakeError.log".
after did:  export JAVA_HOME=<path_to_jdk>
this error appeared.
but i got 
CMake Error at CMakeLists.txt:28 (add_subdirectory):
  The source directory

    /home/gg/BoofCPP/gtest

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/gg/BoofCPP/build/CMakeFiles/CMakeOutput.log".
root@ggjiang:/home/gg/BoofCPP/build# cmake -DCMAKE_BUILD_TYPE=Release .
-- Release Mode --
-- JNI_INCLUDE_DIRS=/usr/lib/jvm/java-8-openjdk-amd64/include;/usr/lib/jvm/java-8-openjdk-amd64/include/linux;/usr/lib/jvm/java-8-openjdk-amd64/include
-- JNI_LIBRARIES=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjawt.so;/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
CMake Error at CMakeLists.txt:28 (add_subdirectory):
  The source directory

    /home/gg/BoofCPP/gtest

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/gg/BoofCPP/build/CMakeFiles/CMakeOutput.log".

I don't know what i should do. 
can you help me please?

**Comment by jgqandsh** [comment]
I solved my error
I run 
git submodule update --init --recursive
the error does not appear
thank you!

**Comment by BrUSomania** [comment]
> I solved my error I run git submodule update --init --recursive the error does not appear thank you!

Thank you, my man! I had the exact same problem and this solved it :)

**Comment by fajin0** [comment]
> I solved my error I run git submodule update --init --recursive the error does not appear thank you!

解决了，十分感谢
git submodule update --init --recursive命令用于初始化和更新Git存储库中的子模块。

这个命令有两部分功能：

--init选项会初始化所有存在但尚未初始化的子模块。它会根据.gitmodules文件中定义的URL克隆子模块的存储库，并将其检出到指定的提交。
--recursive选项会递归地初始化和更新所有嵌套的子模块。如果某个子模块本身也包含子模块，那么这些嵌套的子模块也将被初始化和更新。
执行该命令会使得Git运行以下操作：

检查.gitmodules文件，该文件记录了仓库中的子模块信息。
如果存在尚未初始化的子模块，则使用URL克隆子模块的存储库，并将其检出到指定的提交。
对已经初始化的子模块，使用各自存储库的配置来更新它们。
